### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by xcrezd** [dennisjzh/GwtMobile-PhoneGap#3]
Hi, 

when im working in my eclipse, i want to debug the gwt mobile code with all phonegap capability, how can i do this ( and see my app on android emulator )?

**Comment by dennisjzh** [comment]
Hi xcrezd,

First of all, you will not be able to debug your code on the Android emulator. The reason is simple, there is no gwt developer plugin for Android.

While that is a bad news, I found myself be able to use the desktop chrome browser for most of my debugging needs. That is because gwt mobile behaves mostly the same on both the desktop and the device.

Now, if you need to test your app with phonegap capability, you will need the ripple plugin for Chrome. Last time I tried, I was able to get half of the phonegap functions to work. I recommend you to give it a shot.
http://ripple.tinyhippos.com/

I am closing this issue as it is actually a question. If you have additional questions about gwt mobile, you can post it on the gwt mobile group (link below). If you find issues related to gwt mobile as you try out the ripple plugin, post them here and I will re-open this issue.
http://groups.google.com/group/gwtmobile
